services:
  ecommerce:
    container_name: spike_ecommerce
    labels:
      - traefik.enable=true
      - traefik.http.routers.ecommerce.rule=Host(`shop.srv1175749.hstgr.cloud`) || Host(`puntoclaveshop.com.mx`) || Host(`www.puntoclaveshop.com.mx`)
      - traefik.http.routers.ecommerce.tls=true
      - traefik.http.routers.ecommerce.entrypoints=web,websecure
      - traefik.http.routers.ecommerce.tls.certresolver=mytlschallenge
      - traefik.http.services.ecommerce.loadbalancer.server.port=3000
      - traefik.docker.network=shop_proxy
    networks:
      - shop_proxy

networks:
  shop_proxy:
    external: true
